// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_access_tokenSchema = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: "string",
          pattern: "^password$",
        },
        {
          type: "null",
        },
      ],
      title: "Grant Type",
    },
    username: {
      type: "string",
      title: "Username",
    },
    password: {
      type: "string",
      format: "password",
      title: "Password",
    },
    scope: {
      type: "string",
      title: "Scope",
      default: "",
    },
    client_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Id",
    },
    client_secret: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      format: "password",
      title: "Client Secret",
    },
  },
  type: "object",
  required: ["username", "password"],
  title: "Body_login_access_token",
} as const

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const

export const HealthCheckSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
    },
    environment: {
      type: "string",
      title: "Environment",
    },
    version: {
      type: "string",
      title: "Version",
    },
    timestamp: {
      type: "string",
      title: "Timestamp",
    },
  },
  type: "object",
  required: ["status", "environment", "version", "timestamp"],
  title: "HealthCheck",
} as const

export const ItemCreateSchema = {
  properties: {
    title: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Title",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
  },
  type: "object",
  required: ["title"],
  title: "ItemCreate",
} as const

export const ItemPublicSchema = {
  properties: {
    created_at: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Created At",
    },
    updated_at: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Updated At",
    },
    title: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Title",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    owner_id: {
      type: "integer",
      title: "Owner Id",
    },
  },
  type: "object",
  required: ["title", "id", "owner_id"],
  title: "ItemPublic",
} as const

export const ItemUpdateSchema = {
  properties: {
    title: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Title",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
  },
  type: "object",
  title: "ItemUpdate",
} as const

export const ItemsPublicSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/ItemPublic",
      },
      type: "array",
      title: "Data",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["data", "count"],
  title: "ItemsPublic",
} as const

export const JobSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
    },
  },
  type: "object",
  required: ["id"],
  title: "Job",
} as const

export const MessageSchema = {
  properties: {
    message: {
      type: "string",
      title: "Message",
    },
  },
  type: "object",
  required: ["message"],
  title: "Message",
  description: "Generic message response schema",
} as const

export const PaginatedResponseSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/UserRead",
      },
      type: "array",
      title: "Data",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["data", "count"],
  title: "PaginatedResponse",
} as const

export const ReadyCheckSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
    },
    environment: {
      type: "string",
      title: "Environment",
    },
    version: {
      type: "string",
      title: "Version",
    },
    app: {
      type: "string",
      title: "App",
    },
    database: {
      type: "string",
      title: "Database",
    },
    timestamp: {
      type: "string",
      title: "Timestamp",
    },
  },
  type: "object",
  required: [
    "status",
    "environment",
    "version",
    "app",
    "database",
    "timestamp",
  ],
  title: "ReadyCheck",
} as const

export const TokenSchema = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
    },
    token_type: {
      type: "string",
      title: "Token Type",
    },
  },
  type: "object",
  required: ["access_token", "token_type"],
  title: "Token",
} as const

export const UpdatePasswordSchema = {
  properties: {
    current_password: {
      type: "string",
      title: "Current Password",
    },
    new_password: {
      type: "string",
      title: "New Password",
    },
  },
  type: "object",
  required: ["current_password", "new_password"],
  title: "UpdatePassword",
} as const

export const UserCreateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 30,
          minLength: 2,
        },
        {
          type: "null",
        },
      ],
      title: "Name",
      examples: ["User Userson"],
    },
    username: {
      anyOf: [
        {
          type: "string",
          maxLength: 20,
          minLength: 2,
          pattern: "^[a-z0-9]+$",
        },
        {
          type: "null",
        },
      ],
      title: "Username",
      examples: ["userson"],
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
      examples: ["user.userson@example.com"],
    },
    password: {
      type: "string",
      title: "Password",
      examples: ["Str1ngst!"],
    },
    confirm_password: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Confirm Password",
    },
    is_superuser: {
      type: "boolean",
      title: "Is Superuser",
      default: false,
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
  },
  type: "object",
  required: ["email", "password"],
  title: "UserCreate",
} as const

export const UserReadSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      examples: ["1"],
    },
    full_name: {
      type: "string",
      maxLength: 30,
      minLength: 2,
      title: "Full Name",
      examples: ["User Userson"],
    },
    username: {
      type: "string",
      maxLength: 20,
      minLength: 2,
      pattern: "^[a-z0-9]+$",
      title: "Username",
      examples: ["userson"],
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
      examples: ["user.userson@example.com"],
    },
    profile_image_url: {
      type: "string",
      title: "Profile Image Url",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
    },
    is_superuser: {
      type: "boolean",
      title: "Is Superuser",
    },
  },
  type: "object",
  required: [
    "id",
    "full_name",
    "username",
    "email",
    "profile_image_url",
    "is_active",
    "is_superuser",
  ],
  title: "UserRead",
} as const

export const UserUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 30,
          minLength: 2,
        },
        {
          type: "null",
        },
      ],
      title: "Name",
      examples: ["User Userberg"],
    },
    username: {
      anyOf: [
        {
          type: "string",
          maxLength: 20,
          minLength: 2,
          pattern: "^[a-z0-9]+$",
        },
        {
          type: "null",
        },
      ],
      title: "Username",
      examples: ["userberg"],
    },
    email: {
      anyOf: [
        {
          type: "string",
          format: "email",
        },
        {
          type: "null",
        },
      ],
      title: "Email",
      examples: ["user.userberg@example.com"],
    },
    profile_image_url: {
      anyOf: [
        {
          type: "string",
          pattern: "^(https?|ftp)://[^\\s/$.?#].[^\\s]*$",
        },
        {
          type: "null",
        },
      ],
      title: "Profile Image Url",
      examples: ["https://www.profileimageurl.com"],
    },
    password: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Password",
    },
    confirm_password: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Confirm Password",
    },
    is_active: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Active",
    },
    is_superuser: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Superuser",
    },
  },
  type: "object",
  title: "UserUpdate",
} as const

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const
