// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  HealthApiV1HealthGetResponse,
  ReadyApiV1ReadyGetResponse,
  ReadItemsData,
  ReadItemsResponse,
  CreateItemData,
  CreateItemResponse,
  ReadItemData,
  ReadItemResponse,
  UpdateItemData,
  UpdateItemResponse,
  DeleteItemData,
  DeleteItemResponse,
  LoginAccessTokenData,
  LoginAccessTokenResponse,
  RefreshAccessTokenResponse,
  LogoutData,
  LogoutResponse,
  CreateTaskApiV1TasksTaskPostData,
  CreateTaskApiV1TasksTaskPostResponse,
  GetTaskApiV1TasksTaskTaskIdGetData,
  GetTaskApiV1TasksTaskTaskIdGetResponse,
  CreateUserData,
  CreateUserResponse,
  ReadUsersData,
  ReadUsersResponse,
  ReadUserMeResponse,
  DeleteUserMeResponse,
  UpdateUserMeData,
  UpdateUserMeResponse,
  UpdatePasswordMeData,
  UpdatePasswordMeResponse,
  ReadUserByIdData,
  ReadUserByIdResponse,
  UpdateUserData,
  UpdateUserResponse,
  DeleteUserData,
  DeleteUserResponse,
  DeleteDbUserData,
  DeleteDbUserResponse,
} from "./types.gen"

export class HealthService {
  /**
   * Health
   * Basic health check to verify the application is up.
   * @returns HealthCheck Successful Response
   * @throws ApiError
   */
  public static healthApiV1HealthGet(): CancelablePromise<HealthApiV1HealthGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/health",
    })
  }

  /**
   * Ready
   * Readiness check to verify external dependencies (DB) are available.
   * @returns ReadyCheck Successful Response
   * @throws ApiError
   */
  public static readyApiV1ReadyGet(): CancelablePromise<ReadyApiV1ReadyGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/ready",
    })
  }
}

export class ItemsService {
  /**
   * Read Items
   * Retrieve items.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ItemsPublic Successful Response
   * @throws ApiError
   */
  public static readItems(
    data: ReadItemsData = {},
  ): CancelablePromise<ReadItemsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Item
   * Create new item.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static createItem(
    data: CreateItemData,
  ): CancelablePromise<CreateItemResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/items/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Item
   * Get item by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static readItem(
    data: ReadItemData,
  ): CancelablePromise<ReadItemResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Item
   * Update an item.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static updateItem(
    data: UpdateItemData,
  ): CancelablePromise<UpdateItemResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Item
   * Delete an item.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteItem(
    data: DeleteItemData,
  ): CancelablePromise<DeleteItemResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login For Access Token
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginAccessTokenData,
  ): CancelablePromise<LoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Refresh Access Token
   * @returns string Successful Response
   * @throws ApiError
   */
  public static refreshAccessToken(): CancelablePromise<RefreshAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/refresh",
    })
  }

  /**
   * Logout
   * Logout user and invalidate all outstanding tokens.
   * @param data The data for the request.
   * @param data.refreshToken
   * @returns string Successful Response
   * @throws ApiError
   */
  public static logout(
    data: LogoutData = {},
  ): CancelablePromise<LogoutResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/logout",
      cookies: {
        refresh_token: data.refreshToken,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class TasksService {
  /**
   * Create Task
   * Create a new background task.
   * @param data The data for the request.
   * @param data.message
   * @returns Job Successful Response
   * @throws ApiError
   */
  public static createTaskApiV1TasksTaskPost(
    data: CreateTaskApiV1TasksTaskPostData,
  ): CancelablePromise<CreateTaskApiV1TasksTaskPostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/tasks/task",
      query: {
        message: data.message,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Task
   * Get information about a specific background task.
   * @param data The data for the request.
   * @param data.taskId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getTaskApiV1TasksTaskTaskIdGet(
    data: GetTaskApiV1TasksTaskTaskIdGetData,
  ): CancelablePromise<GetTaskApiV1TasksTaskTaskIdGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/tasks/task/{task_id}",
      path: {
        task_id: data.taskId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Write User
   * Create a new user with generated username if missing (Superuser only).
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserRead Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: CreateUserData,
  ): CancelablePromise<CreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Users
   * Retrieve users with pagination.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns PaginatedResponse Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: ReadUsersData = {},
  ): CancelablePromise<ReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Users Me
   * Get current user information.
   * @returns UserRead Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<ReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user account.
   * @returns string Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<DeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update current user profile.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserRead Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UpdateUserMeData,
  ): CancelablePromise<UpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update current user password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns string Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UpdatePasswordMeData,
  ): CancelablePromise<UpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by ID.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserRead Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: ReadUserByIdData,
  ): CancelablePromise<ReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Patch User
   * Update a specific user profile (Self or Superuser).
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserRead Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UpdateUserData,
  ): CancelablePromise<UpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Erase User
   * Delete a user profile (Self or Superuser).
   * @param data The data for the request.
   * @param data.userId
   * @returns string Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: DeleteUserData,
  ): CancelablePromise<DeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Erase Db User
   * Permanently delete a user from the database (Superuser only).
   * @param data The data for the request.
   * @param data.username
   * @returns string Successful Response
   * @throws ApiError
   */
  public static deleteDbUser(
    data: DeleteDbUserData,
  ): CancelablePromise<DeleteDbUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/db_user/{username}",
      path: {
        username: data.username,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}
