// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type HealthCheck = {
  status: string
  environment: string
  version: string
  timestamp: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  created_at?: string | null
  updated_at?: string | null
  title: string
  description?: string | null
  id: number
  owner_id: number
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type Job = {
  id: string
}

/**
 * Generic message response schema
 */
export type Message = {
  message: string
}

export type PaginatedResponse = {
  data: Array<UserRead>
  count: number
}

export type ReadyCheck = {
  status: string
  environment: string
  version: string
  app: string
  database: string
  timestamp: string
}

export type Token = {
  access_token: string
  token_type: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  name?: string | null
  username?: string | null
  email: string
  password: string
  confirm_password?: string | null
  is_superuser?: boolean
  is_active?: boolean
}

export type UserRead = {
  id: string
  full_name: string
  username: string
  email: string
  profile_image_url: string
  is_active: boolean
  is_superuser: boolean
}

export type UserUpdate = {
  name?: string | null
  username?: string | null
  email?: string | null
  profile_image_url?: string | null
  password?: string | null
  confirm_password?: string | null
  is_active?: boolean | null
  is_superuser?: boolean | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type HealthApiV1HealthGetResponse = HealthCheck

export type ReadyApiV1ReadyGetResponse = ReadyCheck

export type ReadItemsData = {
  limit?: number
  skip?: number
}

export type ReadItemsResponse = ItemsPublic

export type CreateItemData = {
  requestBody: ItemCreate
}

export type CreateItemResponse = ItemPublic

export type ReadItemData = {
  id: number
}

export type ReadItemResponse = ItemPublic

export type UpdateItemData = {
  id: number
  requestBody: ItemUpdate
}

export type UpdateItemResponse = ItemPublic

export type DeleteItemData = {
  id: number
}

export type DeleteItemResponse = Message

export type LoginAccessTokenData = {
  formData: Body_login_access_token
}

export type LoginAccessTokenResponse = Token

export type RefreshAccessTokenResponse = {
  [key: string]: string
}

export type LogoutData = {
  refreshToken?: string | null
}

export type LogoutResponse = {
  [key: string]: string
}

export type CreateTaskApiV1TasksTaskPostData = {
  message: string
}

export type CreateTaskApiV1TasksTaskPostResponse = Job

export type GetTaskApiV1TasksTaskTaskIdGetData = {
  taskId: string
}

export type GetTaskApiV1TasksTaskTaskIdGetResponse = {
  [key: string]: unknown
} | null

export type CreateUserData = {
  requestBody: UserCreate
}

export type CreateUserResponse = UserRead

export type ReadUsersData = {
  limit?: number
  skip?: number
}

export type ReadUsersResponse = PaginatedResponse

export type ReadUserMeResponse = UserRead

export type DeleteUserMeResponse = {
  [key: string]: string
}

export type UpdateUserMeData = {
  requestBody: UserUpdate
}

export type UpdateUserMeResponse = UserRead

export type UpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UpdatePasswordMeResponse = {
  [key: string]: string
}

export type ReadUserByIdData = {
  userId: number
}

export type ReadUserByIdResponse = UserRead

export type UpdateUserData = {
  requestBody: UserUpdate
  userId: number
}

export type UpdateUserResponse = UserRead

export type DeleteUserData = {
  userId: number
}

export type DeleteUserResponse = {
  [key: string]: string
}

export type DeleteDbUserData = {
  username: string
}

export type DeleteDbUserResponse = {
  [key: string]: string
}
